### PR TITLE
Add UMD loader + return boxfit

### LINKED ISSUE #8: Add AMD/CJS support
This plugin is missing AMD/CJS support and returning itself to avoid loading jquery + boxfit.

I could do a PR if you want.

### PR DESCRIPTION
**Pull request by JSteunou**
Should fix #8 

Tested with your demo page for global and a modified page for requirejs, works fine.

Added `define` to jshint global because of the AMD test.

### CODE REVIEW

**Comment by michikono** [comment]
Thanks. I really need to get around to writing tests...

**Comment by JSteunou** [comment]
humm you closed it without merging it ;)

**Comment by michikono** [comment]
Oops. :) need more morning coffee...

Merged and re-tagged.

**Comment by JSteunou** [comment]
Hehe, I cannot PR coffee :D

**Pull request merged**
