### PR TITLE
Made it work with queries returning multiple elements, also it's possible to run box fit for the same element again (so you can update the text)

### PR DESCRIPTION
**Pull request by pawelniewie**

### CODE REVIEW

**Comment by ciaranj** [comment]
+1 this PR fixes the issues I was seeing, this library does _exactly_ what I wanted now :) Thank you (both)!

**Comment by JSteunou** [comment]
+1

I found the same issue, and fix the same. Running on multiple elements is a plus.
Any chance you will consider this PR @michikono ?

**Comment by joshuapaling** [comment]
+1 I actually came here to fork this plugin and add this functionality myself - luckily I noticed it's already been added here!

**Comment by michikono** [comment]
This has been accepted and I have subsequently significantly updated the documentation and demo pages.

**Comment by JSteunou** [comment]
Seen that, great work! Good to see you dont let this plugin die, thank you @michikono!

**Comment by pawelniewie** [comment]
:+1:

**Pull request merged**
